apiVersion: v1
kind: ServiceAccount
metadata:
  name: krathub-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kratos-registry-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kratos-registry-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: krathub-sa
    namespace: default
roleRef:
  kind: Role
  name: kratos-registry-role
  apiGroup: rbac.authorization.k8s.io
