server:
  grpc:
    addr: "${GADDR:0.0.0.0:8080}"
    # timeout: "${GTIMEHOUT:1s}"

app:
  name: sayhello
  version: v1.0.0
  env: "${ENV:dev}"
  log:
    level: "${LOG_LEVEL:-1}"
    filename: "${LOG_FILENAME:sayhello.log}"
    max_size: "${LOG_MAX_SIZE:20}"
    max_age: "${LOG_MAX_AGE:30}"
    max_backups: "${LOG_MAX_BACKUPS:10}"
